-- Phase 5: Monitor & Asset System Tables
-- Apply this against DEV and PROD environments.

-- 1. Asset Host Table
CREATE TABLE IF NOT EXISTS `asset_host` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL COMMENT '资产名称',
  `label` varchar(200) DEFAULT NULL COMMENT '标签/别名',
  `primary_ip` varchar(100) DEFAULT NULL COMMENT '主IP',
  `ipv6` varchar(200) DEFAULT NULL COMMENT 'IPv6地址',
  `environment` varchar(50) DEFAULT NULL COMMENT '环境 (prod/staging/dev)',
  `provider` varchar(100) DEFAULT NULL COMMENT '供应商 (如: AWS, Alibaba, BandwagonHost)',
  `region` varchar(100) DEFAULT NULL COMMENT '区域',
  `role` varchar(100) DEFAULT NULL COMMENT '角色/用途',
  `os` varchar(200) DEFAULT NULL COMMENT '操作系统',
  `cpu_cores` int(10) DEFAULT NULL COMMENT 'CPU核心数',
  `mem_total_mb` int(10) DEFAULT NULL COMMENT '内存(MB)',
  `disk_total_gb` int(10) DEFAULT NULL COMMENT '磁盘(GB)',
  `bandwidth_mbps` int(10) DEFAULT NULL COMMENT '带宽(Mbps)',
  `monthly_traffic_gb` int(10) DEFAULT NULL COMMENT '月流量(GB)',
  `ssh_port` int(10) DEFAULT NULL COMMENT 'SSH端口',
  `purchase_date` bigint(20) DEFAULT NULL COMMENT '购入日期',
  `expire_date` bigint(20) DEFAULT NULL COMMENT '到期日期',
  `monthly_cost` varchar(50) DEFAULT NULL COMMENT '月费用',
  `currency` varchar(10) DEFAULT NULL COMMENT '货币',
  `tags` varchar(500) DEFAULT NULL COMMENT '标签(逗号分隔)',
  `gost_node_id` bigint(20) DEFAULT NULL COMMENT '关联的GOST节点ID',
  `monitor_node_uuid` varchar(100) DEFAULT NULL COMMENT '关联的探针节点UUID',
  `remark` text DEFAULT NULL COMMENT '备注',
  `created_time` bigint(20) NOT NULL COMMENT '创建时间',
  `updated_time` bigint(20) DEFAULT NULL COMMENT '更新时间',
  `status` int(10) NOT NULL DEFAULT 0 COMMENT '状态(0正常 1删除)',
  PRIMARY KEY (`id`),
  KEY `idx_monitor_node_uuid` (`monitor_node_uuid`),
  KEY `idx_gost_node_id` (`gost_node_id`),
  KEY `idx_primary_ip` (`primary_ip`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='服务器资产表';

-- 2. Monitor Instance Table (探针实例 - 如 Komari/Pika 服务端)
CREATE TABLE IF NOT EXISTS `monitor_instance` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL COMMENT '实例名称',
  `type` varchar(50) NOT NULL DEFAULT 'komari' COMMENT '探针类型 (komari/pika)',
  `base_url` varchar(500) NOT NULL COMMENT '服务端地址',
  `api_key` varchar(500) DEFAULT NULL COMMENT 'API密钥',
  `sync_enabled` int(2) NOT NULL DEFAULT 1 COMMENT '是否启用自动同步',
  `sync_interval_minutes` int(10) NOT NULL DEFAULT 5 COMMENT '同步间隔(分钟)',
  `allow_insecure_tls` int(2) NOT NULL DEFAULT 0 COMMENT '允许不安全TLS',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `last_sync_at` bigint(20) DEFAULT NULL COMMENT '最后同步时间',
  `last_sync_status` varchar(20) DEFAULT 'never' COMMENT '最后同步状态 (never/success/failed)',
  `last_sync_error` text DEFAULT NULL COMMENT '最后同步错误信息',
  `node_count` int(10) NOT NULL DEFAULT 0 COMMENT '节点总数',
  `online_node_count` int(10) NOT NULL DEFAULT 0 COMMENT '在线节点数',
  `created_time` bigint(20) NOT NULL COMMENT '创建时间',
  `updated_time` bigint(20) DEFAULT NULL COMMENT '更新时间',
  `status` int(10) NOT NULL DEFAULT 0 COMMENT '状态(0正常 1删除)',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='探针实例表';

-- 3. Monitor Node Snapshot Table (从探针同步来的节点快照)
CREATE TABLE IF NOT EXISTS `monitor_node_snapshot` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `instance_id` bigint(20) NOT NULL COMMENT '所属探针实例ID',
  `remote_node_uuid` varchar(100) NOT NULL COMMENT '远程节点UUID',
  `asset_id` bigint(20) DEFAULT NULL COMMENT '关联的资产ID',
  `name` varchar(200) DEFAULT NULL COMMENT '节点名称',
  `ip` varchar(100) DEFAULT NULL COMMENT 'IPv4地址',
  `ipv6` varchar(200) DEFAULT NULL COMMENT 'IPv6地址',
  `os` varchar(200) DEFAULT NULL COMMENT '操作系统',
  `cpu_name` varchar(200) DEFAULT NULL COMMENT 'CPU名称',
  `cpu_cores` int(10) DEFAULT NULL COMMENT 'CPU核心数',
  `mem_total` bigint(20) DEFAULT NULL COMMENT '总内存(bytes)',
  `disk_total` bigint(20) DEFAULT NULL COMMENT '总磁盘(bytes)',
  `region` varchar(100) DEFAULT NULL COMMENT '区域',
  `version` varchar(50) DEFAULT NULL COMMENT 'Agent版本',
  `virtualization` varchar(100) DEFAULT NULL COMMENT '虚拟化类型',
  `arch` varchar(50) DEFAULT NULL COMMENT 'CPU架构',
  `kernel_version` varchar(200) DEFAULT NULL COMMENT '内核版本',
  `gpu_name` varchar(200) DEFAULT NULL COMMENT 'GPU名称',
  `swap_total` bigint(20) DEFAULT NULL COMMENT '总Swap(bytes)',
  `hidden` int(2) DEFAULT 0 COMMENT '是否隐藏',
  `tags` varchar(500) DEFAULT NULL COMMENT '标签',
  `node_group` varchar(100) DEFAULT NULL COMMENT '分组',
  `weight` int(10) DEFAULT NULL COMMENT '权重/排序',
  `price` double DEFAULT NULL COMMENT '价格',
  `billing_cycle` int(10) DEFAULT NULL COMMENT '计费周期',
  `currency` varchar(10) DEFAULT NULL COMMENT '货币',
  `expired_at` bigint(20) DEFAULT NULL COMMENT '到期时间',
  `traffic_limit` bigint(20) DEFAULT NULL COMMENT '流量限制',
  `traffic_limit_type` varchar(50) DEFAULT NULL COMMENT '流量限制类型',
  `online` int(2) NOT NULL DEFAULT 0 COMMENT '在线状态(0离线 1在线)',
  `last_active_at` bigint(20) DEFAULT NULL COMMENT '最后活跃时间',
  `last_sync_at` bigint(20) DEFAULT NULL COMMENT '最后同步时间',
  `created_time` bigint(20) NOT NULL COMMENT '创建时间',
  `updated_time` bigint(20) DEFAULT NULL COMMENT '更新时间',
  `status` int(10) NOT NULL DEFAULT 0 COMMENT '状态(0正常 1已移除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_uuid` (`instance_id`, `remote_node_uuid`),
  KEY `idx_asset_id` (`asset_id`),
  KEY `idx_online` (`online`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='探针节点快照表';

-- 4. Monitor Metric Latest Table (节点最新指标数据)
CREATE TABLE IF NOT EXISTS `monitor_metric_latest` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `node_snapshot_id` bigint(20) DEFAULT NULL COMMENT '节点快照ID',
  `instance_id` bigint(20) NOT NULL COMMENT '探针实例ID',
  `remote_node_uuid` varchar(100) NOT NULL COMMENT '远程节点UUID',
  `cpu_usage` double DEFAULT NULL COMMENT 'CPU使用率(%)',
  `mem_used` bigint(20) DEFAULT NULL COMMENT '已用内存(bytes)',
  `mem_total` bigint(20) DEFAULT NULL COMMENT '总内存(bytes)',
  `disk_used` bigint(20) DEFAULT NULL COMMENT '已用磁盘(bytes)',
  `disk_total` bigint(20) DEFAULT NULL COMMENT '总磁盘(bytes)',
  `net_in` bigint(20) DEFAULT NULL COMMENT '实时下行(bytes/s)',
  `net_out` bigint(20) DEFAULT NULL COMMENT '实时上行(bytes/s)',
  `net_total_up` bigint(20) DEFAULT NULL COMMENT '累计上行(bytes)',
  `net_total_down` bigint(20) DEFAULT NULL COMMENT '累计下行(bytes)',
  `swap_used` bigint(20) DEFAULT NULL COMMENT '已用Swap(bytes)',
  `swap_total` bigint(20) DEFAULT NULL COMMENT '总Swap(bytes)',
  `gpu_usage` double DEFAULT NULL COMMENT 'GPU使用率(%)',
  `temperature` double DEFAULT NULL COMMENT '温度(°C)',
  `load1` double DEFAULT NULL COMMENT '1分钟负载',
  `load5` double DEFAULT NULL COMMENT '5分钟负载',
  `load15` double DEFAULT NULL COMMENT '15分钟负载',
  `uptime` bigint(20) DEFAULT NULL COMMENT '运行时间(秒)',
  `connections` int(10) DEFAULT NULL COMMENT 'TCP连接数',
  `connections_udp` int(10) DEFAULT NULL COMMENT 'UDP连接数',
  `process_count` int(10) DEFAULT NULL COMMENT '进程数',
  `sampled_at` bigint(20) DEFAULT NULL COMMENT '采样时间',
  `created_time` bigint(20) NOT NULL COMMENT '创建时间',
  `updated_time` bigint(20) DEFAULT NULL COMMENT '更新时间',
  `status` int(10) NOT NULL DEFAULT 0 COMMENT '状态(0正常 1删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_instance_uuid` (`instance_id`, `remote_node_uuid`),
  KEY `idx_node_snapshot_id` (`node_snapshot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='探针节点最新指标表';
